GET http://localhost:8080/ciudades

###

GET http://localhost:8080/ciudad/1

###

GET http://localhost:8080/aeropuertos

###

GET http://localhost:8080/aeropuerto/1

###

GET http://localhost:8080/conexiones

###

GET http://localhost:8080/conexiones/1/5

###

GET http://localhost:8080/aeropuerto/3/conexiones