name: "aeropuertos"
services:
  php:
    image: php:fpm
    build: ./php
    volumes:
      - ./public:/var/www/html
      - ./src:/var/www/src
      - ./php/conf.d/99-xdebug.ini:/usr/local/etc/php/conf.d/99-xdebug.ini
    environment:
      - MYSQL_HOST=mysql # nombre del servicio mysql en docker-compose
      - MYSQL_USER=alumno
      - MYSQL_PASSWORD=alumno
      - MYSQL_DATABASE=aeropuerto
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html
      - ./src/logs:/var/www/src/logs
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: administrador
      MYSQL_USER: alumno
      MYSQL_PASSWORD: alumno
      MYSQL_DATABASE: aeropuerto
    volumes:
      - ./src/db/create.sql:/docker-entrypoint-initdb.d/init.sql
      - ./src/db/insert.sql:/docker-entrypoint-initdb.d/init1.sql
      - ./mysql/data:/var/lib/mysql
      # - ./mysql/tmp:/tmp
    ports:
      - "3306:3306"
    networks:
      - default

networks:
  default:
    driver: bridge
